services:
  app:
    build:
      context: ./ # Le contexte de construction devrait être le répertoire contenant votre Dockerfile
      dockerfile: Dockerfile # Le nom du Dockerfile à utiliser
    container_name: my-php-app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my-mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/blog_db.sql:/docker-entrypoint-initdb.d/blog_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: arogeiro
      MYSQL_DATABASE: blog_db
      MYSQL_USER: arogeiro
      MYSQL_PASSWORD: arogeiro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: arogeiro

volumes:
  mysql-data: